service: fanout

provider:
  name: aws
  runtime: nodejs4.3
  region: ${env:AWS_REGION}
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "arn:aws:lambda:${env:AWS_REGION}:*:function:fanout-${opt:stage}-ResizeImage"
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::brianz-image-resize-fanout-results/*"

functions:
  UploadImage:
    handler: handler.uploadImage
    events:
      - s3:
          bucket: brianz-image-resize-fanout
          event: s3:ObjectCreated:*
  ResizeImage:
    handler: handler.resizeImage

plugins:
  - serverless-prune-plugin
